language: c
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common libglib2.0-dev libjson-glib-dev
    libyaml-dev libgee-0.8-dev libvala-0.22-dev valac-0.22 gobject-introspection
script:
  - ./autogen.sh
  - make
